### ISSUE TITLE
Hours are not Accurate

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ucd-library-hours-week#1]
The google calendars, that reflect the hours don't seem to be completely accurate.  Eg.  Yesterday's (May 28) holiday is not represented.

**Comment by spelkey-ucd** [comment]
All elements are still pulling from example calendars. I had Hector create new calendars with our generic Google account, and am currently populating them with accurate hours (through summer). I will redirect the elements when finished.

**Comment by qjhart** [comment]
Closing, since I don't think this repo is still used, and this should be in the ucd issues page.
