### ISSUE TITLE
staff.library.ucdavis.edu needs an Calendar editing page

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ucd-library-hours-week#3]
We need to create a page on the internal web that describes the process of updating the calendars for the library website, gives pointers to the calendars, and also shows who has editing capabilities.  This needs to be coordinated with Robin for completeness.

**Comment by spelkey-ucd** [comment]
Started a page here: https://staff.library.ucdavis.edu/dept/itis/applications-and-reports/library-hours-management/

**Comment by qjhart** [comment]
@wrenaria  This page looks pretty complete.  Can we touch base w/ Robin that they can help admin this after this first go round.  Good pointer for Law Library too, though honestly, I don't know if they are staff at all :)

**Comment by wrenaria** [comment]
Looks good! I'll reach out to Robin.
